<html>
<head>
    <title>Adicione imagem</title>
    <link rel="stylesheet" href="./css/style.css">
</head>
<body>
<h1>Nova Imagem</h1>

<form class="pure-form" method="post" action="/home/new">
    <label for="name">Nome da imagem</label>        
    <input name="name" id="name" type="text" size="60" /><br/>


    <label for="title">Titulo</label>
    <input name="title" id="title" type="text" size="60" /><br />

    <label for="description">Descrição</label>
    <input name="description" id="description" type="text" size="100" /><br />

    <input type="submit" class="pure-button" value="Salvar" />
</form>

</body>
</html>