<?php 
    $row =  count($res);

    $atual = (isset($_GET['pg'])) ?intval($_GET['pg']) : 1;
    $pagArquivo = array_chunk($res, $limit);
    $contar = count($pagArquivo);
    $resultado =  $pagArquivo[$atual -1];

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Galeria de Imagens</title>
    <link rel="stylesheet" href="./css/style.css">
</head>
<body>

<header class="header">
        <a href="#"><img id="imgLogo" src="./imagens/logo.png" alt="RGB"></a>
        
        <div class="menuPag">
            <div class="mobile-menu">
                <div class="line1"></div>
                <div class="line2"></div>
                <div class="line3"></div>
            </div>
            <div class="phone">
                <h3><small>(00)</small> <?php echo $abt2[0]['telefone'];?></h3>
            </div>
            <div class="paginacao">
                <nav>
                    <ul class="menu">
                        <?php
                            for($i = 1; $i < $contar; $i++){
                                if($i == $atual) {
                                    echo '<li><a href="#">Pagina '.$i.'</a></li>';
                                }else {
                                    echo '<li><a href="?pg='.$i.'">Pagina '.$i.'</a></li>';
                                }
                            }
                        ?>
                    </ul>
                </nav>
            </div>
        </div>
    </header>

    <hr>

    <section class="flex row">        
        <?php           

            foreach($resultado as $valor) {
                echo '<div class="column">';
                echo '<img class="hover-shadow" src="./imagens/'.$valor['nome'].'.jpg" onclick="openModal(this.id);currentSlide('.$valor['id'].')" height="165px">';
                echo '<h3>'.$valor['titulo'].'</h3>';
                echo '<p>'.$valor['descricao'].'</p>';
                echo '<hr>';
                echo '</div>';
            }
        ?>
    </section>

    <section class="infoEmpresa">
        <div class="infoEmpresa-item">
            <img src="./imagens/img-empresa.jpg" alt="Empresa">
        </div>
        <div class="infoEmpresa-item">
            <h4>Pessoa ou Empresa</h4>
            <p><?php echo $abt2[0]['sobre'];?></p>
        </div>
        <div class="infoEmpresa-item">
            <p>Facebook</p><br>
            <p>Email</p>
        </div>
    </section>

    <!-- The Modal/Lightbox -->
    <div id="myModal" class="modal">
    <span class="close cursor" onclick="closeModal()">&times;</span>
    <div class="modal-content">

        <?php 
            for($i = 0; $i < $row; $i ++) {
                echo '<div class="mySlides">';
                echo '<img class="img_modal" src="./imagens/'.$res[$i]['nome'].'.jpg">';
                echo '</div>';
            }
        ?>
    </div>
    </div>

<script src="./js/app.js"></script>
</body>
</html>